import Navbar from "@/components/Navbar/Navbar";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import localFont from "next/font/local";

const robotoSlabLight = localFont({
  src: "../fonts/RobotoSlab-Light.ttf",
  variable: "--font-robotoslab-light",
  weight: "100 900",
});

const robotoSlabRegular = localFont({
  src: "../fonts/RobotoSlab-Regular.ttf",
  variable: "--font-robotoslab-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Fake Store",
  description: "Generated by Reza Rad",
};

export default async function RootLayout({ children, params: { locale } }) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  console.log(locale);

  return (
    <NextIntlClientProvider messages={messages}>
      {children}
    </NextIntlClientProvider>
  );
}
